"""Initial migration

Revision ID: ce7b16a62155
Revises: 
Create Date: 2026-08-17 00:27:00.210073

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import Text


# revision identifiers, used by Alembic.
revision = 'ce7b16a62155'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pledge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sex', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('father_or_husband', sa.String(), nullable=False),
    sa.Column('family_details', postgresql.JSON(astext_type=Text()), nullable=False),
    sa.Column('education', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('occupation', sa.String(), nullable=False),
    sa.Column('intro', sa.String(), nullable=False),
    sa.Column('pledge_details', sa.String(), nullable=False),
    sa.Column('pledge_date', sa.Date(), nullable=False),
    sa.Column('pledge_amounts', sa.Float(), nullable=False),
    sa.Column('bill_no', sa.String(), nullable=False),
    sa.Column('repayment', sa.String(), nullable=False),
    sa.Column('repayment_details', sa.Integer(), nullable=True),
    sa.Column('repayment_schedule', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('total_grams_pending', sa.Float(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('alt_number', sa.String(), nullable=True),
    sa.Column('return_jewellary', sa.String(), nullable=True),
    sa.Column('balance_jewellary', sa.String(), nullable=True),
    sa.Column('hc_claim_form_number', sa.String(), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('aadhar_number', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bill_no')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pledge')
    # ### end Alembic commands ###
